amnis-invictus/ikt.edu.vn.ua

app/assets/javascripts/data-accept-names.js, app/assets/javascripts/direct-upload.js, app/assets/stylesheets/direct-upload.css, app/models/solution.rb, app/models/task.rb, app/views/uploads/edit.html.erb
- show progress using direct upload
- set `accept` attribute from allowed file's extensions
- validate file names on client before upload
=> Improve file upload

app/models/contest.rb, app/views/users/_form.html.erb, spec/features/resgistration_spec.rb, spec/support/form_helpers.rb
=> Contest without sites and cities

app/views/statistics/index.html.erb, app/views/widgets/_sidebar_items.html.erb, db/migrate/20220217094714_add_statistic_open_to_contests.rb, db/structure.sql
Signed-off-by: Kostiantyn Kostiuk <kostyanf14@live.com>
=> Add statistic open flag to contests

.github/workflows/lint.yml, Gemfile, Gemfile.lock
Signed-off-by: Kostiantyn Kostiuk <konstantin@daynix.com>
=> Update RuboCop CI config

app/views/uploads/new.html.erb
=> Add user secret input validation on client side

app/channels/api_channel.rb, app/controllers/uploads_controller.rb, app/models/upload.rb, app/models/user.rb, db/migrate/20221017055914_add_unique_index_users_on_secret_and_contest_id.rb, db/migrate/20221019173456_add_unique_index_users_on_judge_secret_and_contest_id.rb, db/structure.sql
=> User and judge secret uniqueness

app/channels/api_channel.rb
resolve: amnis-invictus/score.judge.ikt.edu.vn.ua#94
Signed-off-by: Kostiantyn Kostiuk <kostyanf14@live.com>
=> API: Provide contest/task name onReady

app/models/solution.rb, config/locales/uk.yml
=> Add solution file size validation

app/channels/api_channel.rb, app/channels/application_cable/connection.rb, app/services/redis_lock_manager.rb, db/migrate/20230121191926_add_scoring_open_to_task.rb, db/structure.sql
Resolve https://github.com/amnis-invictus/score.judge.ikt.edu.vn.ua/issues/90
=> Scoring open 1

Gemfile, Gemfile.lock, app/services/spreadsheet/base.rb, app/services/spreadsheet/judge.rb, app/services/spreadsheet/public.rb, config/initializers/rails_admin.rb, config/locales/en.yml, lib/rails_admin/config/actions/spreadsheet_judge.rb, lib/rails_admin/config/actions/spreadsheet_public.rb
resolves: https://github.com/amnis-invictus/ikt.edu.vn.ua/issues/229
Signed-off-by: Konstantin Kostiuk <kkostiuk@redhat.com>
=> RFC: Admin UI: Add ability to generate XLSX results

app/views/admin/checksum_duplicates.html.erb, app/views/admin/device_ids_mismatch.erb, app/views/admin/ips_mismatch.html.erb, lib/rails_admin/config/actions/device_ids_mismatch.rb, lib/rails_admin/config/actions/ips_mismatch.rb
In general penalty screens are used by judges and judges can't check information with an upload secret.
Signed-off-by: Kostiantyn Kostiuk <kostyanf14@live.com>
=> Use judge secret in penalty screens

app/assets/stylesheets/form.css, app/controllers/uploads_controller.rb, app/models/solution.rb, app/models/upload.rb, app/views/uploads/edit.html.erb
Resolves: https://github.com/amnis-invictus/ikt.edu.vn.ua/issues/266
=> Solution upload page enhancement

app/channels/api_channel.rb
API for https://github.com/amnis-invictus/score.judge.ikt.edu.vn.ua/pull/160
=> Add API for judges list

config/environments/production.rb
fixes Uglifier::Error: Unexpected token: keyword (const).
=> Configure js compressor to support ES6 syntax

.github/workflows/assets-precompile.yml
Signed-off-by: Konstantin Kostiuk <kkostiuk@redhat.com>
=> CI: Check Assets Precompile

app/channels/api_channel.rb
resolves https://github.com/amnis-invictus/score.judge.ikt.edu.vn.ua/issues/113
=> Add notification when finished without errors

app/controllers/judges_controller.rb, app/views/results/index.html.erb, config/routes.rb
=> Add judge result generate button into judge UI

app/assets/javascripts/rails_admin/custom/ui.js, app/models/spreadsheet/config_public.rb, app/services/spreadsheet/public.rb, app/views/admin/spreadsheet_public.html.erb, lib/rails_admin/config/actions/spreadsheet_public.rb
=> Add XLSX result builder

app/services/spreadsheet/public.rb
=> Fix calls to `add_row`

app/mailers/user_mailer.rb
=> Specify locale in UserMailer

app/assets/javascripts/rails_admin/custom/data-action-prefill.js, app/assets/javascripts/rails_admin/custom/grade-groups.js, app/assets/javascripts/rails_admin/custom/ui.js, app/models/grade.rb, app/models/spreadsheet/config_public.rb, app/services/spreadsheet/base.rb, app/services/spreadsheet/judge.rb, app/services/spreadsheet/public.rb, app/types/json_type.rb, app/views/admin/spreadsheet_public.html.erb, app/views/users/_form.html.erb, config/initializers/inflections.rb, config/initializers/types.rb
=> Implement grade groups for XLSX results

Gemfile, Gemfile.lock, config/application.rb
=> Fix deprecated option assign to many

app/models/user.rb, app/views/uploads/new.html.erb, db/migrate/20250113065202_change_secrets_to_citext.rb, db/structure.sql
=> Allow case-insensitive user and registration secret

app/views/admin/spreadsheet_public.html.erb
=> Add new header for the public spreadsheet
